### PR TITLE
Allow RA and Dec to be nullable

### PR DESCRIPTION
**Pull request by dannygoldstein**
This PR removes the nonnull constraint from RA and Dec, accommodating models in Skyportal such as `Photometry` which sometimes have coordinate information supplied and other times not

### CODE REVIEW

**Comment by lpsinger** [comment]
We want ra and dec to be sometimes nullable, and sometimes not. How do we do that?

**Comment by dannygoldstein** [comment]
One could use a class factory, e.g., 

```
def HasPointFactory(nullable=False):
     class Wrapped:
         lat = Column(nullable=nullable)
         lon = Column(nullable=nullable)
     return Wrapped
```

**Comment by lpsinger** [comment]
Is there a way that we could simply allow the user's model class to supply the ra and dec columns? That would kill two birds with one stone: allowing the names to be adjustable, and allowing the columns to be nullable or not.

```python
class Catalog(Base):
    ra = Column(Float, nullable=True)
    dec = Column(Float, nullabele = True)
    point = UnitSphericalCoordinate(ra, dec)
```

**Comment by dannygoldstein** [comment]
@lpsinger  Requesting new release after merge, 0.1.2.

**Pull request merged**
