### PR TITLE
Factor cone search into separate package

### PR DESCRIPTION
**Pull request by lpsinger**
The Cartesian indexing cone search strategy is not going to share any code at all with the HEALPix indexing. Factor the cone search code into a separate package:

https://github.com/skyportal/conesearch-alchemy

### CODE REVIEW

**Comment by profjsb** [comment]
I'm fine with this refactor.

**Review by mcoughlin — APPROVED** [review]
After the discussion on the SP yesterday, this refactoring makes sense.

**Review by profjsb — APPROVED** [review]

**Comment by lpsinger** [comment]
Super, thanks! Merging and releasing conesearch-alchemy now.

**Comment by lpsinger** [comment]
https://pypi.org/project/conesearch-alchemy/

**Pull request merged**
